### ISSUE TITLE
Spring-Boot-Blog

### ISSUE THREAD

**Issue by lightnine** [sheepmen/Spring-Boot-Blog#1]
你好:
最近看到你的博客,看到这个样式,感觉挺喜欢,想问你这个样式在哪里抠出来的呢,能不能给些参考,最近我也在使用spring-boot jpa Hibernate mysql开发自己的个人博客,谢谢!

**Comment by eddiexux** [comment]
我是用的Amaze-UI里示例的改的，后来发现可以用现成的模板 http://tpl.amazeui.org/

最近忙着校招无心看github，很抱歉现在才回复你....
